### ISSUE TITLE
sys_inactive_file/sys_active_file 内容中的宏写反了

### ISSUE THREAD

**Issue by xiaoaniubi** [OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8650#1]
![image](https://github.com/user-attachments/assets/8d775dea-d60e-4bd8-90f8-e7b8f2ffd2e3)

**Comment by OnePlusOSSAdmin** [comment]
感谢您的反馈，我们会在后续版本修正这个问题。

**Comment by chandu078** [comment]
Hello @OnePlusOSSAdmin, it seems the OSS kernel source is broken, and we are unable to boot the OSS kernel. Could you please recheck and test OSS kernel source?

**Comment by MandySingh3** [comment]
Hello @OnePlusOSSAdmin, Im getting error for file prepare_vendor.sh can you please help me with this.  

`
mandy_singh@mandy-singh:~/android/PixelOS/kernel/Oneplus/tools/build/bazel_wrapper$ sudo bash build.sh
[sudo] password for mandy_singh: 
+ KERNEL_PARAM=waipio
+ BUILD_VARIANT=user
+ SOC_VARIANT=QCOM
+++ dirname -- build.sh
++ cd -- .
++ pwd
+ SCRIPT_REAL_PATH=/home/mandy_singh/android/PixelOS/kernel/Oneplus/tools/build/bazel_wrapper
++ realpath /home/mandy_singh/android/PixelOS/kernel/Oneplus/tools/build/bazel_wrapper/../../../../
+ SRC_TOP_REAL_PATH=/home/mandy_singh/android/PixelOS/kernel
+ BZL_TOOL=/home/mandy_singh/android/PixelOS/kernel/prebuilts/build-tools/path/linux-x86/bazel
+ BAZEL_OUTPUT_REAL_PATH=/home/mandy_singh/android/PixelOS/kernel/out/bazel_output
+ WORKSPACE_REAL_PATH=/home/mandy_singh/android/PixelOS/kernel/out/bazel_workspace/kernel
+ KERNEL_PLATFORM_REAL_PATH=/home/mandy_singh/android/PixelOS/kernel/kernel_platform
+ OLD_ENVIRONMENT_REAL_PATH=/home/mandy_singh/android/PixelOS/kernel/out/bazel_workspace/kernel/environment
+ GKI_ABI_FILE_REAL_PATH=/home/mandy_singh/android/PixelOS/kernel/kernel_platform/oplus/config/abi_gki_aarch64_oplus_internal
+ QCOM_GKI_ABI_FILE_REAL_PATH=/home/mandy_singh/android/PixelOS/kernel/kernel_platform/msm-kernel/android/abi_gki_aarch64_qcom
+ KERNEL_OUT_DIR=out
+ GKI_PREBUILTS_DIR=prebuilts/gki-kernel-binaries
+ KERNEL_PLATFORM_RELATIVE_PATH=../../../../kernel_platform
+ '[' waipio == waipio ']'
+ GKI_KERNEL_BINARIES_RELATIVE_PATH=../../../../kernel_platform/out/msm-waipio-waipio-gki/gki_kernel/dist
+ OLD_ENVIRONMENT_RELATIVE_PATH=../../../bazel_workspace/kernel/environment
+ BUILD_KERNEL_COMMAND='kernel_platform/build/android/prepare_vendor.sh waipio gki'
+ BUILD_KERNEL_WITH_PREBUILT_GKB_COMMAND='GKI_PREBUILTS_DIR=prebuilts/gki-kernel-binaries kernel_platform/build/android/prepare_vendor.sh waipio gki'
+ rm -rf /home/mandy_singh/android/PixelOS/kernel/out/bazel_output
+ rm -rf /home/mandy_singh/android/PixelOS/kernel/out/bazel_workspace/kernel
++ dirname /home/mandy_singh/android/PixelOS/kernel/out/bazel_workspace/kernel
+ mkdir -p /home/mandy_singh/android/PixelOS/kernel/out/bazel_workspace
+ cp -rf /home/mandy_singh/android/PixelOS/kernel/Oneplus/tools/build/bazel_wrapper/ /home/mandy_singh/android/PixelOS/kernel/out/bazel_workspace/kernel
+ cp -rf /home/mandy_singh/android/PixelOS/kernel/kernel_platform/oplus/config/abi_gki_aarch64_oplus_internal /home/mandy_singh/android/PixelOS/kernel/out/bazel_workspace/kernel
+ cp -rf /home/mandy_singh/android/PixelOS/kernel/kernel_platform/msm-kernel/android/abi_gki_aarch64_qcom /home/mandy_singh/android/PixelOS/kernel/out/bazel_workspace/kernel
+ export -p
+ '[' '!' -f /home/mandy_singh/android/PixelOS/kernel/prebuilts/build-tools/path/linux-x86/bazel ']'
+ echo 'can not find bazel tools, build kernel directly'
can not find bazel tools, build kernel directly
+ build_kernel
+ echo ========================================================
========================================================
+ echo ' Build kernel'
 Build kernel
+ eval kernel_platform/build/android/prepare_vendor.sh waipio gki
++ kernel_platform/build/android/prepare_vendor.sh waipio gki
build.sh: line 65: kernel_platform/build/android/prepare_vendor.sh: No such file or directory
+ exit
`

**Comment by OnePlusOSSAdmin** [comment]
@MandySingh3 Prepare build environment as this manifest:
https://git.codelinaro.org/clo/la/kernelplatform/manifest/-/blob/KERNEL.PLATFORM.3.0.r1-07400-kernel.0/KERNEL.PLATFORM.3.0.r1-07400-kernel.0.xml?ref_type=tags
You should get kernel_platform/build/android/prepare_vendor.sh 

export 
TARGET_BOARD_PLATFORM=pineapple
PRODUCT_DEVICE=pineapple

kernel_platform/build/android/prepare_vendor.sh pineapple gki

**Comment by MandySingh3** [comment]
Thank you, I will try to compile the kernel again and post update.

**Comment by athanatos1** [comment]
I am also having difficulties in compiling the kernel. It seems some files are missing such as:
cp: cannot stat '/home/owner/android/op12/kernel_platform/oplus/config/**abi_gki_aarch64_oplus_internal**': No such file or directory

I also made a few comments on the other source tree thread: https://github.com/OnePlusOSS/android_kernel_oneplus_sm8650/tree/oneplus/sm8650_u_14.0.0_oneplus12

Please oneplus / Oppo, we are trying to compile this kernel and it's proving difficult without the whole source. 

I am trying to compile pineapple, not wapio

**Comment by OnePlusOSSAdmin** [comment]
./kernel_platform/oplus/build/oplus_build_kernel.sh pineapple gki
Please try it after we update code tommorrow. Now you could use v version code to check if there's something wrong still.

**Comment by athanatos1** [comment]
> ./kernel_platform/oplus/build/oplus_build_kernel.sh pineapple gki Please try it after we update code tommorrow. Now you could use v version code to check if there's something wrong still.

Thank you for updating the code, but I am still missing this config file: abi_gki_aarch64_oplus_internal'

ERROR: /home/owner/android/op12/out/bazel_workspace/kernel/bazel/BUILD:2:5: Executing genrule //:kernel failed: missing input file '//:abi_gki_aarch64_oplus_internal'
ERROR: /home/owner/android/op12/out/bazel_workspace/kernel/bazel/BUILD:2:5: Executing genrule //:kernel failed: 1 input file(s) do not exist

@OnePlusOSSAdmin

**Comment by OnePlusOSSAdmin** [comment]
Please refer to https://github.com/OnePlusOSS/android_kernel_oneplus_sm8650/issues/9#issuecomment-2477877870
